project:
  type: website
  output-dir: docs

website:
  navbar:
    title: ""
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications      
      - href: presentations.qmd
        text: Presentations      

format:
  html:
    theme:
      - quartz
      - styles.scss
    toc: true
    mainfont: Aptos, sans-serif
    fontsize: 0.95em
    fontcolor: "#f5f5f5"
    margin-top: 0px

editor: source
